use crate::ir::*;
use crate::query::walk::{for_each_outgoing_edge, Edge, Node};
use crate::query::workflow_run as wr;
use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet, VecDeque};

/// External-finding overlay for `graph --highlight findings`, keyed by node id.
///
/// Built by `cmd_graph` from the M1 pipeline; the renderer consumes only plain
/// strings (a compact count badge + a Mermaid `style` body) so the query layer
/// stays decoupled from the CLI overlay types. Nodes absent from the maps
/// render exactly as before.
#[derive(Debug, Default)]
pub struct GraphOverlay {
    pub workflows: HashMap<String, GraphNodeOverlay>,
    pub actions: HashMap<String, GraphNodeOverlay>,
}

/// Per-node overlay: `badge` is appended to the node label (`<br/>H:2 M:1`);
/// `style` is the Mermaid `style <id> <style>` body (e.g. `fill:#…,stroke:#…`).
#[derive(Debug, Default, Clone)]
pub struct GraphNodeOverlay {
    pub badge: String,
    pub style: String,
}

/// Append a count badge to a node label as a `<br/>`-separated line.
fn with_badge(label: String, overlay: Option<&GraphNodeOverlay>) -> String {
    match overlay {
        Some(o) if !o.badge.is_empty() => format!("{label}<br/>{}", escape_label(&o.badge)),
        _ => label,
    }
}

const KNOWN_TRIGGER_ORDER: &[&str] = &[
    "push",
    "pull_request",
    "schedule",
    "workflow_dispatch",
    "workflow_run",
];

/// Render an IR as a Mermaid `graph LR` document.
///
/// `scope` filters entry-point workflows to those matching the given event.
/// When `scope` is `Some(event)` and zero entry-points match, the body is a
/// single `%% (no entry-point matches event <event>)` comment so callers
/// always see a parseable Mermaid v10+ document with the expected header.
//
// `collapsible_match` would collapse `Some(UsesRef::X(t)) => { if guard { ... } }`
// arms into guarded patterns, but doing so would force a `_ => {}` catch-all and
// lose exhaustiveness checking against future `UsesRef` variants.
#[allow(clippy::collapsible_match)]
pub fn render(ir: &Ir, scope: Option<&str>) -> String {
    render_impl(ir, scope, None)
}

/// `render` with a `--highlight findings` overlay: node labels gain a finding
/// count badge and findings-bearing nodes get a severity-colored `style`.
#[allow(clippy::collapsible_match)]
pub fn render_with_findings(ir: &Ir, scope: Option<&str>, overlay: &GraphOverlay) -> String {
    render_impl(ir, scope, Some(overlay))
}

#[allow(clippy::collapsible_match)]
fn render_impl(ir: &Ir, scope: Option<&str>, overlay: Option<&GraphOverlay>) -> String {
    let mut out = String::new();
    // Collected `style <id> <body>` lines for findings-bearing nodes, emitted
    // at graph level after all nodes/edges (style inside `subgraph` is invalid).
    let mut node_styles: Vec<(String, String)> = Vec::new();
    out.push_str("%% generated by ravelact\n");
    out.push_str("graph LR\n");

    // -- ID maps (sorted) ----------------------------------------------------
    let mut wf_sorted: Vec<&Workflow> = ir.workflows.iter().collect();
    wf_sorted.sort_by(|a, b| a.id.0.cmp(&b.id.0));
    let wf_id: HashMap<&str, String> = wf_sorted
        .iter()
        .enumerate()
        .map(|(n, wf)| (wf.id.0.as_str(), format!("wf_{n}")))
        .collect();

    let mut act_sorted: Vec<&LocalAction> = ir.actions.iter().collect();
    act_sorted.sort_by(|a, b| a.id.0.cmp(&b.id.0));
    let act_id: HashMap<&str, String> = act_sorted
        .iter()
        .enumerate()
        .map(|(n, c)| (c.id.0.as_str(), format!("act_{n}")))
        .collect();

    let mut ext_keys_sorted: BTreeSet<ExtKey> = BTreeSet::new();
    for e in &ir.external_actions {
        ext_keys_sorted.insert(ExtKey::from_action_ref(e));
    }
    let ext_id: BTreeMap<ExtKey, String> = ext_keys_sorted
        .iter()
        .enumerate()
        .map(|(n, k)| (k.clone(), format!("ext_{n}")))
        .collect();

    // -- Reachability BFS (orphans-style insert-before-enqueue) --------------
    let wf_lookup: HashMap<&str, &Workflow> =
        ir.workflows.iter().map(|w| (w.id.0.as_str(), w)).collect();
    let act_lookup: HashMap<&str, &LocalAction> =
        ir.actions.iter().map(|c| (c.id.0.as_str(), c)).collect();

    let mut reachable_wf: HashSet<String> = HashSet::new();
    let mut reachable_act: HashSet<String> = HashSet::new();
    let mut reachable_ext: HashSet<ExtKey> = HashSet::new();
    let mut reachable_dock: HashSet<DockerKey> = HashSet::new();
    let mut reachable_extwf: HashSet<ExtWfKey> = HashSet::new();
    let mut queue: VecDeque<NodeRef> = VecDeque::new();

    for wf in &ir.workflows {
        if wf.triggers.iter().any(|t| matches_scope(t, scope))
            && reachable_wf.insert(wf.id.0.clone())
        {
            queue.push_back(NodeRef::Workflow(wf.id.0.clone()));
        }
    }

    while let Some(node) = queue.pop_front() {
        let walk_node = match &node {
            NodeRef::Workflow(id) => wf_lookup.get(id.as_str()).copied().map(Node::Workflow),
            NodeRef::Action(id) => act_lookup.get(id.as_str()).copied().map(Node::Action),
        };
        let Some(walk_node) = walk_node else {
            continue;
        };
        for_each_outgoing_edge(walk_node, |ctx| match ctx.edge {
            Edge::Annotation(ann) => {
                if let AnnotationResolution::Resolved { target } = &ann.resolution {
                    if reachable_wf.insert(target.0.clone()) {
                        queue.push_back(NodeRef::Workflow(target.0.clone()));
                    }
                }
            }
            Edge::CallsWorkflow(call) => match &call.workflow_ref {
                WorkflowRef::Local(t) => {
                    if reachable_wf.insert(t.0.clone()) {
                        queue.push_back(NodeRef::Workflow(t.0.clone()));
                    }
                }
                WorkflowRef::External {
                    owner,
                    repo,
                    path,
                    gitref,
                } => {
                    reachable_extwf.insert(ExtWfKey {
                        owner: owner.clone(),
                        repo: repo.clone(),
                        path: path.clone(),
                        gitref: gitref.clone(),
                    });
                }
            },
            Edge::Uses(uses) => match uses {
                UsesRef::LocalWorkflow(t) => {
                    if reachable_wf.insert(t.0.clone()) {
                        queue.push_back(NodeRef::Workflow(t.0.clone()));
                    }
                }
                UsesRef::LocalAction(t) => {
                    if reachable_act.insert(t.0.clone()) {
                        queue.push_back(NodeRef::Action(t.0.clone()));
                    }
                }
                UsesRef::External {
                    owner,
                    repo,
                    subpath,
                    gitref,
                } => {
                    reachable_ext.insert(ExtKey {
                        owner: owner.clone(),
                        repo: repo.clone(),
                        subpath: subpath.clone(),
                        gitref: gitref.clone(),
                    });
                }
                UsesRef::Docker(d) => {
                    reachable_dock.insert(DockerKey::from_docker_ref(d));
                }
            },
        });
    }

    // Drop reachable ids that do not exist in the IR. These come from
    // dangling local `uses:` references (e.g. `uses: ./.github/actions/typo`).
    // Wiring surfaces them as `DanglingLocalUses` findings; the graph emits
    // a `%% unresolved` comment instead of panicking on the missing lookup.
    let mut unresolved_uses: BTreeSet<String> = BTreeSet::new();
    reachable_wf.retain(|id| {
        if wf_lookup.contains_key(id.as_str()) {
            true
        } else {
            unresolved_uses.insert(format!("local-workflow: {id}"));
            false
        }
    });
    reachable_act.retain(|id| {
        if act_lookup.contains_key(id.as_str()) {
            true
        } else {
            unresolved_uses.insert(format!("local-action: {id}"));
            false
        }
    });

    // Empty-scope short-circuit.
    if let Some(e) = scope {
        if reachable_wf.is_empty() {
            out.push_str(&format!("%% (no entry-point matches event {e})\n"));
            return out;
        }
    }

    // -- External workflow ID map (sorted; built from BFS reachability) -------
    let extwf_keys_sorted: BTreeSet<ExtWfKey> = reachable_extwf.iter().cloned().collect();
    let extwf_id: BTreeMap<ExtWfKey, String> = extwf_keys_sorted
        .iter()
        .enumerate()
        .map(|(n, k)| (k.clone(), format!("extwf_{n}")))
        .collect();

    // -- Docker container action ID map (sorted; built from BFS reachability) -
    let dock_keys_sorted: BTreeSet<DockerKey> = reachable_dock.iter().cloned().collect();
    let dock_id: BTreeMap<DockerKey, String> = dock_keys_sorted
        .iter()
        .enumerate()
        .map(|(n, k)| (k.clone(), format!("dock_{n}")))
        .collect();

    // -- Subgraphs (per-trigger aliases for entry-point workflows) -----------
    type EntryRow = (String, String); // (wf_id_str, alias_id)
    let mut sub_known: BTreeMap<usize, Vec<EntryRow>> = BTreeMap::new();
    let mut sub_other: BTreeMap<String, Vec<EntryRow>> = BTreeMap::new();

    for wf_id_str in &reachable_wf {
        let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
        for trigger in &wf.triggers {
            if !trigger.is_entry_point() {
                continue;
            }
            if let Some(s) = scope {
                if trigger.event_name() != s {
                    continue;
                }
            }
            let event = trigger.event_name();
            let suffix = sanitize_trigger_id(event);
            let alias = format!("{}__{}", wf_id[wf_id_str.as_str()], suffix);
            let row: EntryRow = (wf_id_str.clone(), alias);

            if let Some(idx) = KNOWN_TRIGGER_ORDER.iter().position(|x| *x == event) {
                sub_known.entry(idx).or_default().push(row);
            } else {
                sub_other.entry(event.to_string()).or_default().push(row);
            }
        }
    }
    for v in sub_known.values_mut() {
        v.sort_by(|a, b| a.1.cmp(&b.1));
    }
    for v in sub_other.values_mut() {
        v.sort_by(|a, b| a.1.cmp(&b.1));
    }

    // -- Canonical-needed determination --------------------------------------
    let mut canonical: HashSet<String> = HashSet::new();
    let mut pure_reusable: HashSet<String> = HashSet::new();
    for wf_id_str in &reachable_wf {
        let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
        let is_pure_reusable = !wf.triggers.iter().any(|t| t.is_entry_point())
            && wf
                .triggers
                .iter()
                .any(|t| t.event == EventKind::WorkflowCall);
        if is_pure_reusable {
            canonical.insert(wf_id_str.clone());
            pure_reusable.insert(wf_id_str.clone());
        }
    }
    // Annotation targets carried by reachable composite actions also become
    // canonical so the graph includes them even when no workflow-side `uses:`
    // structurally references them.
    for act_id_str in &reachable_act {
        let comp = act_lookup.get(act_id_str.as_str()).unwrap();
        for_each_outgoing_edge(Node::Action(comp), |ctx| {
            if let Edge::Annotation(ann) = ctx.edge {
                if let AnnotationResolution::Resolved { target } = &ann.resolution {
                    if reachable_wf.contains(&target.0) {
                        canonical.insert(target.0.clone());
                    }
                }
            }
        });
    }
    for wf_id_str in &reachable_wf {
        let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
        for_each_outgoing_edge(Node::Workflow(wf), |ctx| {
            let target_id: Option<&WorkflowId> = match ctx.edge {
                Edge::Annotation(ann) => match &ann.resolution {
                    AnnotationResolution::Resolved { target } => Some(target),
                    AnnotationResolution::Dangling { .. } => None,
                },
                Edge::CallsWorkflow(call) => match &call.workflow_ref {
                    WorkflowRef::Local(target) => Some(target),
                    WorkflowRef::External { .. } => None,
                },
                Edge::Uses(UsesRef::LocalWorkflow(target)) => Some(target),
                Edge::Uses(_) => None,
            };
            if let Some(target) = target_id {
                if reachable_wf.contains(&target.0) {
                    canonical.insert(target.0.clone());
                }
            }
        });
    }

    // -- workflow_run resolution --------------------------------------------
    // Use the query-layer name index (build_index) so both explicit `name:`
    // fields and path-based fallback names are resolved correctly.
    // Spec: workflow_run.workflows matches by display name; when `name:` is
    // absent the path acts as the effective name.
    // https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
    let wr_name_index = wr::build_index(ir);
    let wr_trigger_idx = KNOWN_TRIGGER_ORDER
        .iter()
        .position(|x| *x == "workflow_run")
        .unwrap();
    let mut wr_edges: Vec<(String, String)> = Vec::new();
    let mut comments: BTreeSet<String> = BTreeSet::new();
    if let Some(rows) = sub_known.get(&wr_trigger_idx).cloned() {
        for (wf_id_str, alias) in rows {
            let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
            for trigger in &wf.triggers {
                if let Some(EventExtras::WorkflowRun { workflows }) = &trigger.extras {
                    for upstream_name in workflows {
                        let targets = wr::resolve_name(&wr_name_index, upstream_name);
                        if targets.is_empty() {
                            comments.insert(format!("workflow_run unresolved: {upstream_name}"));
                        } else {
                            for upstream_id in targets {
                                if reachable_wf.contains(&upstream_id.0) {
                                    wr_edges.push((upstream_id.0.clone(), alias.clone()));
                                    canonical.insert(upstream_id.0.clone());
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    // -- Emit subgraphs ------------------------------------------------------
    for (idx, rows) in &sub_known {
        let event = KNOWN_TRIGGER_ORDER[*idx];
        emit_subgraph(&mut out, event, rows, &wf_lookup, overlay, &mut node_styles);
    }
    for (event, rows) in &sub_other {
        emit_subgraph(&mut out, event, rows, &wf_lookup, overlay, &mut node_styles);
    }

    // -- Emit canonical workflow declarations --------------------------------
    let mut canon_list: Vec<&String> = canonical.iter().collect();
    canon_list.sort_by(|a, b| wf_id[a.as_str()].cmp(&wf_id[b.as_str()]));
    for wf_id_str in canon_list {
        let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
        let node_overlay = overlay.and_then(|o| o.workflows.get(wf_id_str.as_str()));
        let node_id = &wf_id[wf_id_str.as_str()];
        out.push_str(&format!(
            "{}[\"{}\"]\n",
            node_id,
            with_badge(workflow_label(wf), node_overlay)
        ));
        if let Some(o) = node_overlay {
            if !o.style.is_empty() {
                node_styles.push((node_id.clone(), o.style.clone()));
            }
        }
    }

    // -- Composites (reachable only, sorted) ---------------------------------
    let mut act_list: Vec<&String> = reachable_act.iter().collect();
    act_list.sort_by(|a, b| act_id[a.as_str()].cmp(&act_id[b.as_str()]));
    for act_id_str in act_list {
        let c = act_lookup.get(act_id_str.as_str()).unwrap();
        let node_overlay = overlay.and_then(|o| o.actions.get(act_id_str.as_str()));
        let node_id = &act_id[act_id_str.as_str()];
        out.push_str(&format!(
            "{}[\"{}\"]\n",
            node_id,
            with_badge(local_action_label(c), node_overlay)
        ));
        if let Some(o) = node_overlay {
            if !o.style.is_empty() {
                node_styles.push((node_id.clone(), o.style.clone()));
            }
        }
    }

    // -- Externals (reachable only, sorted) ----------------------------------
    let mut ext_list: Vec<&ExtKey> = reachable_ext.iter().collect();
    ext_list.sort();
    for k in ext_list {
        out.push_str(&format!("{}[\"{}\"]\n", ext_id[k], external_label(k)));
    }

    // -- Docker container actions (reachable only, sorted) -------------------
    for k in &dock_keys_sorted {
        out.push_str(&format!(
            "{}[\"{}\"]\n",
            dock_id[k],
            escape_label(&k.display_str())
        ));
    }

    // -- External workflows (reachable only, sorted) -------------------------
    let mut extwf_list: Vec<&ExtWfKey> = reachable_extwf.iter().collect();
    extwf_list.sort();
    for k in extwf_list {
        out.push_str(&format!("{}[\"{}\"]\n", extwf_id[k], external_wf_label(k)));
    }

    // -- Comments (sorted) ---------------------------------------------------
    for c in &comments {
        out.push_str(&format!("%% {c}\n"));
    }
    for c in &unresolved_uses {
        out.push_str(&format!("%% unresolved {c}\n"));
    }

    // -- Edges ---------------------------------------------------------------
    let mut edges: BTreeSet<(String, String, Option<String>)> = BTreeSet::new();

    let collect_outgoing =
        |source: &str, wf: &Workflow, edges: &mut BTreeSet<(String, String, Option<String>)>| {
            for_each_outgoing_edge(Node::Workflow(wf), |ctx| {
                let target_alias = resolve_structural_edge_target(
                    &ctx.edge,
                    &reachable_wf,
                    &reachable_act,
                    &reachable_ext,
                    &reachable_dock,
                    &reachable_extwf,
                    &wf_id,
                    &act_id,
                    &ext_id,
                    &dock_id,
                    &extwf_id,
                );
                if let Some(target) = target_alias {
                    edges.insert((source.to_string(), target, None));
                }
            });
        };

    // Edges from per-trigger aliases.
    for rows in sub_known.values() {
        for (wf_id_str, alias) in rows {
            let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
            collect_outgoing(alias, wf, &mut edges);
        }
    }
    for rows in sub_other.values() {
        for (wf_id_str, alias) in rows {
            let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
            collect_outgoing(alias, wf, &mut edges);
        }
    }

    // Edges from pure-reusable canonical (no entry-point trigger).
    for wf_id_str in &pure_reusable {
        let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
        collect_outgoing(&wf_id[wf_id_str.as_str()], wf, &mut edges);
    }

    // Edges from composites.
    for act_id_str in &reachable_act {
        let c = act_lookup.get(act_id_str.as_str()).unwrap();
        let source = act_id[act_id_str.as_str()].clone();
        for_each_outgoing_edge(Node::Action(c), |ctx| {
            let target_alias = resolve_structural_edge_target(
                &ctx.edge,
                &reachable_wf,
                &reachable_act,
                &reachable_ext,
                &reachable_dock,
                &reachable_extwf,
                &wf_id,
                &act_id,
                &ext_id,
                &dock_id,
                &extwf_id,
            );
            if let Some(target) = target_alias {
                edges.insert((source.clone(), target, None));
            }
        });
    }

    // workflow_run edges.
    for (upstream_id, downstream_alias) in &wr_edges {
        edges.insert((
            wf_id[upstream_id.as_str()].clone(),
            downstream_alias.clone(),
            Some("workflow_run".to_string()),
        ));
    }

    for (from, to, label) in &edges {
        match label {
            Some(l) => out.push_str(&format!("{from} -->|{l}| {to}\n")),
            None => out.push_str(&format!("{from} --> {to}\n")),
        }
    }

    // -- Annotated edges (dotted, with verb label) --------------------------
    // Emitted after structural edges so they overlay the same graph.
    let mut annotated: BTreeSet<(String, String, String)> = BTreeSet::new();

    let collect_annotated_outgoing =
        |source: &str, wf: &Workflow, out: &mut BTreeSet<(String, String, String)>| {
            for_each_outgoing_edge(Node::Workflow(wf), |ctx| {
                if let Edge::Annotation(ann) = ctx.edge {
                    if let AnnotationResolution::Resolved { target } = &ann.resolution {
                        if reachable_wf.contains(&target.0) {
                            out.insert((
                                source.to_string(),
                                wf_id[target.0.as_str()].clone(),
                                verb_label(ann.verb).to_string(),
                            ));
                        }
                    }
                }
            });
        };

    for rows in sub_known.values() {
        for (wf_id_str, alias) in rows {
            let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
            collect_annotated_outgoing(alias, wf, &mut annotated);
        }
    }
    for rows in sub_other.values() {
        for (wf_id_str, alias) in rows {
            let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
            collect_annotated_outgoing(alias, wf, &mut annotated);
        }
    }
    for wf_id_str in &pure_reusable {
        let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
        collect_annotated_outgoing(&wf_id[wf_id_str.as_str()], wf, &mut annotated);
    }

    // Composite-action annotated edges (manifest + per-step), originating from
    // the action node itself. Mirrors the workflow-side walk above so verbs
    // attached to composite carriers show as dotted edges in the graph.
    for act_id_str in &reachable_act {
        let comp = act_lookup.get(act_id_str.as_str()).unwrap();
        let source = act_id[act_id_str.as_str()].clone();
        for_each_outgoing_edge(Node::Action(comp), |ctx| {
            if let Edge::Annotation(ann) = ctx.edge {
                if let AnnotationResolution::Resolved { target } = &ann.resolution {
                    if reachable_wf.contains(&target.0) {
                        annotated.insert((
                            source.clone(),
                            wf_id[target.0.as_str()].clone(),
                            verb_label(ann.verb).to_string(),
                        ));
                    }
                }
            }
        });
    }

    if !annotated.is_empty() {
        for (from, to, label) in &annotated {
            out.push_str(&format!("{from} -. {label} .-> {to}\n"));
        }
        out.push_str("classDef ravelactAnnotation stroke:#dca,stroke-dasharray:5 5\n");
    }

    // -- Finding-overlay node styles (graph level, after all nodes) ----------
    node_styles.sort();
    for (id, style) in &node_styles {
        out.push_str(&format!("style {id} {style}\n"));
    }

    out
}

fn verb_label(v: AnnotationVerb) -> &'static str {
    match v {
        AnnotationVerb::Dispatches => "dispatches",
        AnnotationVerb::Triggers => "triggers",
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

#[derive(Debug)]
enum NodeRef {
    Workflow(String),
    Action(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
struct ExtKey {
    owner: String,
    repo: String,
    subpath: Option<String>,
    gitref: String,
}

impl ExtKey {
    fn from_action_ref(e: &ExternalActionRef) -> Self {
        ExtKey {
            owner: e.owner.clone(),
            repo: e.repo.clone(),
            subpath: e.subpath.clone(),
            gitref: e.gitref.clone(),
        }
    }
}

/// Key for a cross-repo reusable workflow node (`uses: owner/repo/.github/workflows/X.yml@ref`).
/// Distinct from [`ExtKey`] which identifies external *action* steps.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
struct ExtWfKey {
    owner: String,
    repo: String,
    /// Full path within the repo, e.g. `.github/workflows/deploy.yml`.
    path: String,
    gitref: String,
}

/// Key for a Docker container action ref (`uses: docker://[host/]image[:tag]`).
/// Mirrors `ExtKey` for the canonical-node + edge rendering path; uniqueness
/// comes from the full (host, image, tag) tuple so registry-distinct images
/// remain distinct nodes in the rendered graph.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
struct DockerKey {
    host: Option<String>,
    image: String,
    tag: Option<String>,
}

impl DockerKey {
    fn from_docker_ref(d: &DockerRef) -> Self {
        DockerKey {
            host: d.host.clone(),
            image: d.image.clone(),
            tag: d.tag.clone(),
        }
    }

    /// Reuse `DockerRef::display_str()` so `graph` and `trace` cannot drift on
    /// Docker label format (`{host/}{image}{:tag}`).
    fn display_str(&self) -> String {
        DockerRef {
            host: self.host.clone(),
            image: self.image.clone(),
            tag: self.tag.clone(),
        }
        .display_str()
    }
}

fn matches_scope(t: &TriggerSpec, scope: Option<&str>) -> bool {
    if !t.is_entry_point() {
        return false;
    }
    match scope {
        Some(e) => t.event_name() == e,
        None => true,
    }
}

/// Resolve one outgoing edge produced by [`for_each_outgoing_edge`] to a
/// target alias string in the rendered graph, gated by reachability sets so
/// orphan targets (uses-of-uses that the BFS never touched) are dropped.
/// Edges that never carry a structural target — annotation edges, dangling
/// resolutions — return `None`.
#[allow(clippy::too_many_arguments)]
fn resolve_structural_edge_target(
    edge: &Edge<'_>,
    reachable_wf: &HashSet<String>,
    reachable_act: &HashSet<String>,
    reachable_ext: &HashSet<ExtKey>,
    reachable_dock: &HashSet<DockerKey>,
    reachable_extwf: &HashSet<ExtWfKey>,
    wf_id: &HashMap<&str, String>,
    act_id: &HashMap<&str, String>,
    ext_id: &BTreeMap<ExtKey, String>,
    dock_id: &BTreeMap<DockerKey, String>,
    extwf_id: &BTreeMap<ExtWfKey, String>,
) -> Option<String> {
    match edge {
        Edge::Annotation(_) => None,
        Edge::CallsWorkflow(call) => match &call.workflow_ref {
            WorkflowRef::Local(t) => {
                if reachable_wf.contains(&t.0) {
                    Some(wf_id[t.0.as_str()].clone())
                } else {
                    None
                }
            }
            WorkflowRef::External {
                owner,
                repo,
                path,
                gitref,
            } => {
                let key = ExtWfKey {
                    owner: owner.clone(),
                    repo: repo.clone(),
                    path: path.clone(),
                    gitref: gitref.clone(),
                };
                if reachable_extwf.contains(&key) {
                    Some(extwf_id[&key].clone())
                } else {
                    None
                }
            }
        },
        Edge::Uses(uses) => match uses {
            UsesRef::LocalWorkflow(t) => {
                if reachable_wf.contains(&t.0) {
                    Some(wf_id[t.0.as_str()].clone())
                } else {
                    None
                }
            }
            UsesRef::LocalAction(t) => {
                if reachable_act.contains(&t.0) {
                    Some(act_id[t.0.as_str()].clone())
                } else {
                    None
                }
            }
            UsesRef::External {
                owner,
                repo,
                subpath,
                gitref,
            } => {
                let key = ExtKey {
                    owner: owner.clone(),
                    repo: repo.clone(),
                    subpath: subpath.clone(),
                    gitref: gitref.clone(),
                };
                if reachable_ext.contains(&key) {
                    Some(ext_id[&key].clone())
                } else {
                    None
                }
            }
            UsesRef::Docker(d) => {
                let key = DockerKey::from_docker_ref(d);
                if reachable_dock.contains(&key) {
                    Some(dock_id[&key].clone())
                } else {
                    None
                }
            }
        },
    }
}

fn sanitize_trigger_id(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

fn escape_label(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("#quot;"),
            '<' => out.push_str("#lt;"),
            '>' => out.push_str("#gt;"),
            ']' => out.push_str("&#93;"),
            '\n' => out.push_str("<br/>"),
            _ => out.push(c),
        }
    }
    out
}

fn workflow_label(wf: &Workflow) -> String {
    match &wf.name {
        Some(n) => format!("{}<br/>{}", escape_label(&wf.id.0), escape_label(n)),
        None => escape_label(&wf.id.0),
    }
}

fn local_action_label(c: &LocalAction) -> String {
    match &c.name {
        Some(n) => format!("{}<br/>{}", escape_label(&c.id.0), escape_label(n)),
        None => escape_label(&c.id.0),
    }
}

fn external_label(k: &ExtKey) -> String {
    let sub = k
        .subpath
        .as_deref()
        .map(|s| format!("/{s}"))
        .unwrap_or_default();
    escape_label(&format!("{}/{}{}@{}", k.owner, k.repo, sub, k.gitref))
}

fn external_wf_label(k: &ExtWfKey) -> String {
    escape_label(&format!("{}/{}/{}@{}", k.owner, k.repo, k.path, k.gitref))
}

fn emit_subgraph(
    out: &mut String,
    event: &str,
    rows: &[(String, String)],
    wf_lookup: &HashMap<&str, &Workflow>,
    overlay: Option<&GraphOverlay>,
    node_styles: &mut Vec<(String, String)>,
) {
    let id = sanitize_trigger_id(event);
    out.push_str(&format!("subgraph {id}\n"));
    for (wf_id_str, alias) in rows {
        let wf = wf_lookup.get(wf_id_str.as_str()).unwrap();
        let node_overlay = overlay.and_then(|o| o.workflows.get(wf_id_str.as_str()));
        out.push_str(&format!(
            "  {alias}[\"{}\"]\n",
            with_badge(workflow_label(wf), node_overlay)
        ));
        if let Some(o) = node_overlay {
            if !o.style.is_empty() {
                node_styles.push((alias.clone(), o.style.clone()));
            }
        }
    }
    out.push_str("end\n");
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn wf(id: &str, name: Option<&str>, triggers: Vec<TriggerSpec>, jobs: Vec<Job>) -> Workflow {
        Workflow {
            id: WorkflowId(id.into()),
            source: SourcePos {
                file: PathBuf::new(),
                line: None,
            },
            name: name.map(|s| s.to_string()),
            run_name: None,
            triggers,
            jobs,
            permissions: None,
            defaults: None,
            env: Default::default(),
            concurrency: None,
            annotations: Vec::new(),
        }
    }

    fn job_with(id: &str, wf_id: &str, calls: Option<CallsWorkflow>, steps: Vec<Step>) -> Job {
        Job {
            id: JobId(id.into()),
            workflow: WorkflowId(wf_id.into()),
            needs: vec![],
            permissions: None,
            steps,
            calls_workflow: calls,
            runs_on: None,
            outputs: Default::default(),
            source: SourcePos {
                file: PathBuf::new(),
                line: None,
            },
            environment: None,
            if_expr: None,
            strategy: None,
            defaults: None,
            env: Default::default(),
            concurrency: None,
            container: None,
            services: Default::default(),
            annotations: Vec::new(),
        }
    }

    fn step(idx: usize, uses: Option<UsesRef>) -> Step {
        Step {
            index: idx,
            id: None,
            name: None,
            uses,
            run: None,
            if_expr: None,
            with: Default::default(),
            env: Default::default(),
            shell: None,
            working_directory: None,
            timeout_minutes: None,
            continue_on_error: None,
            source: SourcePos {
                file: PathBuf::new(),
                line: None,
            },
            annotations: Vec::new(),
        }
    }

    fn composite(id: &str, name: Option<&str>, steps: Vec<Step>) -> LocalAction {
        LocalAction {
            id: ActionId(id.into()),
            source: SourcePos {
                file: PathBuf::new(),
                line: None,
            },
            name: name.map(|s| s.to_string()),
            kind: ActionKind::Composite,
            inputs: vec![],
            outputs: vec![],
            steps,
            annotations: Vec::new(),
        }
    }

    fn ext_action(owner: &str, repo: &str, gitref: &str) -> ExternalActionRef {
        ExternalActionRef {
            owner: owner.into(),
            repo: repo.into(),
            subpath: None,
            gitref: gitref.into(),
        }
    }

    /// Basic case covering: entry workflow with multi-trigger (push +
    /// pull_request), a pure reusable workflow, a composite, an external
    /// action, a dual-role workflow (workflow_call + schedule), a cycle
    /// (X workflow_call→ Y, Y step→ X local-workflow), a Docker step
    /// (rendered as a canonical `dock_*` node + edges from each reaching
    /// alias, mirroring the External path), and label escaping
    /// (`name: "CI <build>"`).
    #[test]
    fn render_basic_graph() {
        let ext = ext_action("actions", "checkout", "v4");
        // ci.yml: multi-trigger entry, calls build (pure reusable), uses external
        let ci = wf(
            ".github/workflows/ci.yml",
            Some("CI <build>"),
            vec![
                TriggerSpec::bare(EventKind::Push),
                TriggerSpec::bare(EventKind::PullRequest),
            ],
            vec![
                job_with(
                    "test",
                    ".github/workflows/ci.yml",
                    None,
                    vec![
                        step(
                            0,
                            Some(UsesRef::External {
                                owner: "actions".into(),
                                repo: "checkout".into(),
                                subpath: None,
                                gitref: "v4".into(),
                            }),
                        ),
                        step(
                            1,
                            Some(UsesRef::LocalAction(ActionId(
                                ".github/actions/setup".into(),
                            ))),
                        ),
                        // Docker step is rendered as a canonical dock_* node
                        // with edges from each reaching subgraph alias.
                        step(
                            2,
                            Some(UsesRef::Docker(DockerRef {
                                host: None,
                                image: "alpine".into(),
                                tag: Some("3".into()),
                            })),
                        ),
                    ],
                ),
                job_with(
                    "call-build",
                    ".github/workflows/ci.yml",
                    Some(CallsWorkflow {
                        workflow_ref: WorkflowRef::Local(WorkflowId(
                            ".github/workflows/build.yml".into(),
                        )),
                        with: Default::default(),
                        secrets: SecretsPass::Inherit,
                    }),
                    vec![],
                ),
            ],
        );
        // build.yml: pure reusable, calls cycle1 (which calls back into build.yml)
        let build = wf(
            ".github/workflows/build.yml",
            Some("Build"),
            vec![TriggerSpec::bare(EventKind::WorkflowCall)],
            vec![job_with(
                "build",
                ".github/workflows/build.yml",
                Some(CallsWorkflow {
                    workflow_ref: WorkflowRef::Local(WorkflowId(
                        ".github/workflows/cycle.yml".into(),
                    )),
                    with: Default::default(),
                    secrets: SecretsPass::None,
                }),
                vec![],
            )],
        );
        // cycle.yml: pure reusable, step.uses LocalWorkflow → build.yml (cycle)
        let cycle = wf(
            ".github/workflows/cycle.yml",
            None,
            vec![TriggerSpec::bare(EventKind::WorkflowCall)],
            vec![job_with(
                "loop",
                ".github/workflows/cycle.yml",
                None,
                vec![step(
                    0,
                    Some(UsesRef::LocalWorkflow(WorkflowId(
                        ".github/workflows/build.yml".into(),
                    ))),
                )],
            )],
        );
        // dual.yml: dual-role (workflow_call + schedule)
        let dual = wf(
            ".github/workflows/dual.yml",
            None,
            vec![
                TriggerSpec::bare(EventKind::Schedule),
                TriggerSpec::bare(EventKind::WorkflowCall),
            ],
            vec![job_with(
                "dual-job",
                ".github/workflows/dual.yml",
                None,
                vec![step(
                    0,
                    Some(UsesRef::LocalAction(ActionId(
                        ".github/actions/setup".into(),
                    ))),
                )],
            )],
        );

        let setup = composite(
            ".github/actions/setup",
            Some("Setup"),
            vec![step(
                0,
                Some(UsesRef::External {
                    owner: "actions".into(),
                    repo: "checkout".into(),
                    subpath: None,
                    gitref: "v4".into(),
                }),
            )],
        );

        let ir = Ir {
            schema_version: 1,
            root: PathBuf::from("/tmp/test"),
            workflows: vec![ci, build, cycle, dual],
            actions: vec![setup],
            external_actions: vec![ext],
        };

        let out = render(&ir, None);
        let expected = "\
%% generated by ravelact
graph LR
subgraph push
  wf_1__push[\".github/workflows/ci.yml<br/>CI #lt;build#gt;\"]
end
subgraph pull_request
  wf_1__pull_request[\".github/workflows/ci.yml<br/>CI #lt;build#gt;\"]
end
subgraph schedule
  wf_3__schedule[\".github/workflows/dual.yml\"]
end
wf_0[\".github/workflows/build.yml<br/>Build\"]
wf_2[\".github/workflows/cycle.yml\"]
act_0[\".github/actions/setup<br/>Setup\"]
ext_0[\"actions/checkout@v4\"]
dock_0[\"alpine:3\"]
act_0 --> ext_0
wf_0 --> wf_2
wf_1__pull_request --> act_0
wf_1__pull_request --> dock_0
wf_1__pull_request --> ext_0
wf_1__pull_request --> wf_0
wf_1__push --> act_0
wf_1__push --> dock_0
wf_1__push --> ext_0
wf_1__push --> wf_0
wf_2 --> wf_0
wf_3__schedule --> act_0
";
        assert_eq!(out, expected, "rendered output mismatch:\n{out}");
    }

    /// Same IR as `render_basic_graph` reduced to the parts relevant for
    /// `--scope push`. Verifies that pull_request / schedule subgraphs and
    /// nodes that are only reachable through other triggers drop out.
    #[test]
    fn render_scope_push() {
        let ci = wf(
            ".github/workflows/ci.yml",
            None,
            vec![
                TriggerSpec::bare(EventKind::Push),
                TriggerSpec::bare(EventKind::PullRequest),
            ],
            vec![job_with(
                "test",
                ".github/workflows/ci.yml",
                None,
                vec![step(
                    0,
                    Some(UsesRef::LocalAction(ActionId(
                        ".github/actions/setup".into(),
                    ))),
                )],
            )],
        );
        let dual = wf(
            ".github/workflows/dual.yml",
            None,
            vec![
                TriggerSpec::bare(EventKind::Schedule),
                TriggerSpec::bare(EventKind::WorkflowCall),
            ],
            vec![],
        );
        let setup = composite(".github/actions/setup", None, vec![]);

        let ir = Ir {
            schema_version: 1,
            root: PathBuf::from("/tmp/test"),
            workflows: vec![ci, dual],
            actions: vec![setup],
            external_actions: vec![],
        };

        let out = render(&ir, Some("push"));
        let expected = "\
%% generated by ravelact
graph LR
subgraph push
  wf_0__push[\".github/workflows/ci.yml\"]
end
act_0[\".github/actions/setup\"]
wf_0__push --> act_0
";
        assert_eq!(out, expected, "scope-push rendered output mismatch:\n{out}");
    }

    /// `workflow_run` resolution: success / multi-match / unresolved in one IR.
    #[test]
    fn render_workflow_run_resolution() {
        let foo = wf(
            ".github/workflows/foo.yml",
            Some("Foo"),
            vec![TriggerSpec::bare(EventKind::Push)],
            vec![],
        );
        let bar1 = wf(
            ".github/workflows/bar1.yml",
            Some("Bar"),
            vec![TriggerSpec::bare(EventKind::Push)],
            vec![],
        );
        let bar2 = wf(
            ".github/workflows/bar2.yml",
            Some("Bar"),
            vec![TriggerSpec::bare(EventKind::Push)],
            vec![],
        );
        let downstream = wf(
            ".github/workflows/downstream.yml",
            Some("Downstream"),
            vec![TriggerSpec {
                event: EventKind::WorkflowRun,
                branches: RefFilter::None,
                tags: RefFilter::None,
                paths: RefFilter::None,
                types: None,
                extras: Some(EventExtras::WorkflowRun {
                    workflows: vec!["Foo".into(), "Bar".into(), "Missing".into()],
                }),
            }],
            vec![],
        );
        let ir = Ir {
            schema_version: 1,
            root: PathBuf::from("/tmp/test"),
            workflows: vec![foo, bar1, bar2, downstream],
            actions: vec![],
            external_actions: vec![],
        };

        let out = render(&ir, None);
        // sorted by id.0: bar1=wf_0, bar2=wf_1, downstream=wf_2, foo=wf_3
        let expected = "\
%% generated by ravelact
graph LR
subgraph push
  wf_0__push[\".github/workflows/bar1.yml<br/>Bar\"]
  wf_1__push[\".github/workflows/bar2.yml<br/>Bar\"]
  wf_3__push[\".github/workflows/foo.yml<br/>Foo\"]
end
subgraph workflow_run
  wf_2__workflow_run[\".github/workflows/downstream.yml<br/>Downstream\"]
end
wf_0[\".github/workflows/bar1.yml<br/>Bar\"]
wf_1[\".github/workflows/bar2.yml<br/>Bar\"]
wf_3[\".github/workflows/foo.yml<br/>Foo\"]
%% workflow_run unresolved: Missing
wf_0 -->|workflow_run| wf_2__workflow_run
wf_1 -->|workflow_run| wf_2__workflow_run
wf_3 -->|workflow_run| wf_2__workflow_run
";
        assert_eq!(
            out, expected,
            "workflow_run rendered output mismatch:\n{out}"
        );
    }

    #[test]
    fn render_emits_dotted_annotated_edge() {
        // Trigger workflow has a step-anchored Dispatches annotation pointing
        // at a workflow_call-only target. The mermaid output must include the
        // dotted `-. dispatches .->` edge plus the classDef declaration.
        let trigger = wf(
            ".github/workflows/trigger.yml",
            Some("Trigger"),
            vec![TriggerSpec::bare(EventKind::Push)],
            vec![{
                let mut j = job_with(
                    "run",
                    ".github/workflows/trigger.yml",
                    None,
                    vec![step(0, None)],
                );
                j.steps[0].annotations.push(Annotation {
                    verb: AnnotationVerb::Dispatches,
                    resolution: AnnotationResolution::Resolved {
                        target: WorkflowId(".github/workflows/target.yml".into()),
                    },
                    source_line: 6,
                });
                j
            }],
        );
        let target = wf(
            ".github/workflows/target.yml",
            Some("Target"),
            vec![TriggerSpec::bare(EventKind::WorkflowCall)],
            vec![],
        );
        let ir = Ir {
            schema_version: 1,
            root: PathBuf::from("/tmp/test"),
            workflows: vec![trigger, target],
            actions: vec![],
            external_actions: vec![],
        };
        let out = render(&ir, None);
        assert!(
            out.contains("-. dispatches .->"),
            "expected dotted annotated edge, got:\n{out}"
        );
        assert!(
            out.contains("classDef ravelactAnnotation"),
            "expected classDef directive, got:\n{out}"
        );
        // target.yml must be canonical-declared in the graph
        assert!(
            out.contains(".github/workflows/target.yml"),
            "annotation target should appear as a node, got:\n{out}"
        );
    }
}
