// @generated by buffa-codegen. DO NOT EDIT.
// source: ravelact/browse/v1/browse.proto

pub mod if_condition {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Scope<'a> {
        Job(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::JobIfConditionView<'a>,
            >,
        ),
        Step(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::StepIfConditionView<'a>,
            >,
        ),
    }
}
pub mod trace_json_node {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Node<'a> {
        Workflow(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::TraceWorkflowNodeView<'a>,
            >,
        ),
        Action(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::TraceActionNodeView<'a>,
            >,
        ),
        ExternalAction(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::TraceExternalActionNodeView<
                    'a,
                >,
            >,
        ),
        ExternalWorkflow(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::TraceExternalWorkflowNodeView<
                    'a,
                >,
            >,
        ),
        Docker(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::TraceDockerNodeView<'a>,
            >,
        ),
        Annotated(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::TraceAnnotatedNodeView<'a>,
            >,
        ),
        Cycle(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::TraceCycleNodeView<'a>,
            >,
        ),
        Guarded(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::TraceGuardedNodeView<'a>,
            >,
        ),
    }
}
