// @generated by buffa-codegen. DO NOT EDIT.
// source: ravelact/browse/v1/browse.proto

pub mod if_condition {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Scope {
        Job(::buffa::alloc::boxed::Box<super::super::super::JobIfCondition>),
        Step(::buffa::alloc::boxed::Box<super::super::super::StepIfCondition>),
    }
    impl ::buffa::Oneof for Scope {}
    impl From<super::super::super::JobIfCondition> for Scope {
        fn from(v: super::super::super::JobIfCondition) -> Self {
            Self::Job(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::JobIfCondition> for ::core::option::Option<Scope> {
        fn from(v: super::super::super::JobIfCondition) -> Self {
            Self::Some(Scope::from(v))
        }
    }
    impl From<super::super::super::StepIfCondition> for Scope {
        fn from(v: super::super::super::StepIfCondition) -> Self {
            Self::Step(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::StepIfCondition> for ::core::option::Option<Scope> {
        fn from(v: super::super::super::StepIfCondition) -> Self {
            Self::Some(Scope::from(v))
        }
    }
    impl serde::Serialize for Scope {
        fn serialize<S: serde::Serializer>(
            &self,
            s: S,
        ) -> ::core::result::Result<S::Ok, S::Error> {
            use serde::ser::SerializeMap;
            let mut map = s.serialize_map(Some(1))?;
            match self {
                Self::Job(v) => {
                    map.serialize_entry("job", v)?;
                }
                Self::Step(v) => {
                    map.serialize_entry("step", v)?;
                }
            }
            map.end()
        }
    }
}
pub mod trace_json_node {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Node {
        Workflow(::buffa::alloc::boxed::Box<super::super::super::TraceWorkflowNode>),
        Action(::buffa::alloc::boxed::Box<super::super::super::TraceActionNode>),
        ExternalAction(
            ::buffa::alloc::boxed::Box<super::super::super::TraceExternalActionNode>,
        ),
        ExternalWorkflow(
            ::buffa::alloc::boxed::Box<super::super::super::TraceExternalWorkflowNode>,
        ),
        Docker(::buffa::alloc::boxed::Box<super::super::super::TraceDockerNode>),
        Annotated(::buffa::alloc::boxed::Box<super::super::super::TraceAnnotatedNode>),
        Cycle(::buffa::alloc::boxed::Box<super::super::super::TraceCycleNode>),
        Guarded(::buffa::alloc::boxed::Box<super::super::super::TraceGuardedNode>),
    }
    impl ::buffa::Oneof for Node {}
    impl From<super::super::super::TraceWorkflowNode> for Node {
        fn from(v: super::super::super::TraceWorkflowNode) -> Self {
            Self::Workflow(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TraceWorkflowNode> for ::core::option::Option<Node> {
        fn from(v: super::super::super::TraceWorkflowNode) -> Self {
            Self::Some(Node::from(v))
        }
    }
    impl From<super::super::super::TraceActionNode> for Node {
        fn from(v: super::super::super::TraceActionNode) -> Self {
            Self::Action(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TraceActionNode> for ::core::option::Option<Node> {
        fn from(v: super::super::super::TraceActionNode) -> Self {
            Self::Some(Node::from(v))
        }
    }
    impl From<super::super::super::TraceExternalActionNode> for Node {
        fn from(v: super::super::super::TraceExternalActionNode) -> Self {
            Self::ExternalAction(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TraceExternalActionNode>
    for ::core::option::Option<Node> {
        fn from(v: super::super::super::TraceExternalActionNode) -> Self {
            Self::Some(Node::from(v))
        }
    }
    impl From<super::super::super::TraceExternalWorkflowNode> for Node {
        fn from(v: super::super::super::TraceExternalWorkflowNode) -> Self {
            Self::ExternalWorkflow(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TraceExternalWorkflowNode>
    for ::core::option::Option<Node> {
        fn from(v: super::super::super::TraceExternalWorkflowNode) -> Self {
            Self::Some(Node::from(v))
        }
    }
    impl From<super::super::super::TraceDockerNode> for Node {
        fn from(v: super::super::super::TraceDockerNode) -> Self {
            Self::Docker(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TraceDockerNode> for ::core::option::Option<Node> {
        fn from(v: super::super::super::TraceDockerNode) -> Self {
            Self::Some(Node::from(v))
        }
    }
    impl From<super::super::super::TraceAnnotatedNode> for Node {
        fn from(v: super::super::super::TraceAnnotatedNode) -> Self {
            Self::Annotated(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TraceAnnotatedNode> for ::core::option::Option<Node> {
        fn from(v: super::super::super::TraceAnnotatedNode) -> Self {
            Self::Some(Node::from(v))
        }
    }
    impl From<super::super::super::TraceCycleNode> for Node {
        fn from(v: super::super::super::TraceCycleNode) -> Self {
            Self::Cycle(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TraceCycleNode> for ::core::option::Option<Node> {
        fn from(v: super::super::super::TraceCycleNode) -> Self {
            Self::Some(Node::from(v))
        }
    }
    impl From<super::super::super::TraceGuardedNode> for Node {
        fn from(v: super::super::super::TraceGuardedNode) -> Self {
            Self::Guarded(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TraceGuardedNode> for ::core::option::Option<Node> {
        fn from(v: super::super::super::TraceGuardedNode) -> Self {
            Self::Some(Node::from(v))
        }
    }
    impl serde::Serialize for Node {
        fn serialize<S: serde::Serializer>(
            &self,
            s: S,
        ) -> ::core::result::Result<S::Ok, S::Error> {
            use serde::ser::SerializeMap;
            let mut map = s.serialize_map(Some(1))?;
            match self {
                Self::Workflow(v) => {
                    map.serialize_entry("workflow", v)?;
                }
                Self::Action(v) => {
                    map.serialize_entry("action", v)?;
                }
                Self::ExternalAction(v) => {
                    map.serialize_entry("externalAction", v)?;
                }
                Self::ExternalWorkflow(v) => {
                    map.serialize_entry("externalWorkflow", v)?;
                }
                Self::Docker(v) => {
                    map.serialize_entry("docker", v)?;
                }
                Self::Annotated(v) => {
                    map.serialize_entry("annotated", v)?;
                }
                Self::Cycle(v) => {
                    map.serialize_entry("cycle", v)?;
                }
                Self::Guarded(v) => {
                    map.serialize_entry("guarded", v)?;
                }
            }
            map.end()
        }
    }
}
