// @generated by buffa-codegen. DO NOT EDIT.

include!("ravelact.browse.v1.browse.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("ravelact.browse.v1.browse.__view.rs");
        pub mod oneof {
            #[allow(unused_imports)]
            use super::*;
            include!("ravelact.browse.v1.browse.__view_oneof.rs");
        }
    }
    pub mod oneof {
        #[allow(unused_imports)]
        use super::*;
        include!("ravelact.browse.v1.browse.__oneof.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__GET_GRAPH_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GET_GRAPH_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__CY_NODE_JSON_ANY);
        reg.register_json_any(super::__CY_NODE_DATA_JSON_ANY);
        reg.register_json_any(super::__CY_EDGE_JSON_ANY);
        reg.register_json_any(super::__CY_EDGE_DATA_JSON_ANY);
        reg.register_json_any(super::__GET_REPO_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GET_REPO_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__LIST_TRIGGERS_REQUEST_JSON_ANY);
        reg.register_json_any(super::__LIST_TRIGGERS_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__TRIGGER_SUMMARY_JSON_ANY);
        reg.register_json_any(super::__SEARCH_REQUEST_JSON_ANY);
        reg.register_json_any(super::__SEARCH_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__SEARCH_MATCH_JSON_ANY);
        reg.register_json_any(super::__GET_EVENT_IMPACT_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GET_EVENT_IMPACT_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__GET_NODE_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GET_NODE_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__IF_CONDITION_JSON_ANY);
        reg.register_json_any(super::__JOB_IF_CONDITION_JSON_ANY);
        reg.register_json_any(super::__STEP_IF_CONDITION_JSON_ANY);
        reg.register_json_any(super::__GET_IMPACT_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GET_IMPACT_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__IMPACT_ACTION_JSON_ANY);
        reg.register_json_any(super::__TRACE_REQUEST_JSON_ANY);
        reg.register_json_any(super::__TRACE_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__TRACE_JSON_NODE_JSON_ANY);
        reg.register_json_any(super::__TRACE_WORKFLOW_NODE_JSON_ANY);
        reg.register_json_any(super::__TRACE_ACTION_NODE_JSON_ANY);
        reg.register_json_any(super::__TRACE_EXTERNAL_ACTION_NODE_JSON_ANY);
        reg.register_json_any(super::__TRACE_EXTERNAL_WORKFLOW_NODE_JSON_ANY);
        reg.register_json_any(super::__TRACE_DOCKER_NODE_JSON_ANY);
        reg.register_json_any(super::__TRACE_ANNOTATED_NODE_JSON_ANY);
        reg.register_json_any(super::__TRACE_CYCLE_NODE_JSON_ANY);
        reg.register_json_any(super::__TRACE_GUARDED_NODE_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::GetGraphRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetGraphResponseView;
#[doc(inline)]
pub use self::__buffa::view::CyNodeView;
#[doc(inline)]
pub use self::__buffa::view::CyNodeDataView;
#[doc(inline)]
pub use self::__buffa::view::CyEdgeView;
#[doc(inline)]
pub use self::__buffa::view::CyEdgeDataView;
#[doc(inline)]
pub use self::__buffa::view::GetRepoRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetRepoResponseView;
#[doc(inline)]
pub use self::__buffa::view::ListTriggersRequestView;
#[doc(inline)]
pub use self::__buffa::view::ListTriggersResponseView;
#[doc(inline)]
pub use self::__buffa::view::TriggerSummaryView;
#[doc(inline)]
pub use self::__buffa::view::SearchRequestView;
#[doc(inline)]
pub use self::__buffa::view::SearchResponseView;
#[doc(inline)]
pub use self::__buffa::view::SearchMatchView;
#[doc(inline)]
pub use self::__buffa::view::GetEventImpactRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetEventImpactResponseView;
#[doc(inline)]
pub use self::__buffa::view::GetNodeRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetNodeResponseView;
#[doc(inline)]
pub use self::__buffa::view::IfConditionView;
#[doc(inline)]
pub use self::__buffa::view::JobIfConditionView;
#[doc(inline)]
pub use self::__buffa::view::StepIfConditionView;
#[doc(inline)]
pub use self::__buffa::view::GetImpactRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetImpactResponseView;
#[doc(inline)]
pub use self::__buffa::view::ImpactActionView;
#[doc(inline)]
pub use self::__buffa::view::TraceRequestView;
#[doc(inline)]
pub use self::__buffa::view::TraceResponseView;
#[doc(inline)]
pub use self::__buffa::view::TraceJsonNodeView;
#[doc(inline)]
pub use self::__buffa::view::TraceWorkflowNodeView;
#[doc(inline)]
pub use self::__buffa::view::TraceActionNodeView;
#[doc(inline)]
pub use self::__buffa::view::TraceExternalActionNodeView;
#[doc(inline)]
pub use self::__buffa::view::TraceExternalWorkflowNodeView;
#[doc(inline)]
pub use self::__buffa::view::TraceDockerNodeView;
#[doc(inline)]
pub use self::__buffa::view::TraceAnnotatedNodeView;
#[doc(inline)]
pub use self::__buffa::view::TraceCycleNodeView;
#[doc(inline)]
pub use self::__buffa::view::TraceGuardedNodeView;
#[doc(inline)]
pub use self::__buffa::register_types;
